# see https://github.com/vmware/govmomi/releases
# renovate: datasource=github-releases depName=vmware/govmomi
govc_version: '0.30.4'

# see https://github.com/rgl/ovftool-binaries
ovftool_version: '4.5.0-20459872'

# see https://www.powershellgallery.com/packages/VMware.PowerCLI
# see https://developer.vmware.com/web/tool/13.0.0/vmware-powercli
powercli_version: '13.0.0.20829139'
