- name: Add traefik repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Install traefik
  # see https://artifacthub.io/packages/helm/traefik/traefik
  # see https://github.com/traefik/traefik-helm-chart
  # see https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  # see https://github.com/traefik/traefik-helm-chart/blob/master/traefik/Changelog.md
  kubernetes.core.helm:
    name: kube-traefik
    chart_ref: traefik/traefik
    chart_version: '{{ kind_traefik_chart_version }}'
    release_namespace: kube-traefik
    create_namespace: true
    update_repo_cache: true
    values:
      # configure the service.
      service:
        type: LoadBalancer
      # configure the tls options.
      # see https://doc.traefik.io/traefik/https/tls/#tls-options
      # see https://wiki.mozilla.org/Security/Server_Side_TLS
      # see https://ssl-config.mozilla.org
      tlsOptions:
        default:
          sniStrict: true
          minVersion: VersionTLS12
          cipherSuites:
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      # publish the traefik service IP address in the Ingress
      # resources.
      providers:
        kubernetesIngress:
          publishedService:
            enabled: true
      # disable the telemetry.
      # see https://doc.traefik.io/traefik/contributing/data-collection/
      global:
        checkNewVersion: false
        sendAnonymousUsage: false
