# see https://github.com/containers/skopeo/blob/main/install.md

- name: Install skopeo
  ansible.builtin.apt:
    name: skopeo

- name: Install localhost-5000.conf
  ansible.builtin.copy:
    src: libcontainers-localhost-5000.conf
    dest: /etc/containers/registries.conf.d/localhost-5000.conf

- name: Install skopeo bash completion
  block:
    - name: Get skopeo bash completion
      ansible.builtin.shell: skopeo completion bash
      register: bash_completion
      changed_when: false
    - name: Install skopeo bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/skopeo
