# Netherlands datapacket mirror.
# see https://launchpad.net/ubuntu/+archivemirrors
# see https://launchpad.net/ubuntu/+mirror/mirror.nl.datapacket.com-archive
upgrade_ubuntu_apt_sources_url: https://mirror.nl.datapacket.com/ubuntu
