# see https://github.com/hashicorp/vagrant/tags
# renovate: datasource=github-tags depName=hashicorp/vagrant
vagrant_version: '2.3.4'

# see https://rubygems.org/gems/vagrant-libvirt
# see https://github.com/vagrant-libvirt/vagrant-libvirt
# renovate: datasource=rubygems depName=vagrant-libvirt
vagrant_libvirt_plugin_version: '0.12.2'

# see https://rubygems.org/gems/vagrant-reload
# see https://github.com/aidanns/vagrant-reload
# renovate: datasource=rubygems depName=vagrant-reload
vagrant_reload_plugin_version: '0.0.1'

# see https://rubygems.org/gems/vagrant-scp
# see https://github.com/invernizzi/vagrant-scp
# renovate: datasource=rubygems depName=vagrant-scp
vagrant_scp_plugin_version: '0.5.9'

# see https://rubygems.org/gems/vagrant-vsphere
# see https://github.com/nsidc/vagrant-vsphere
# renovate: datasource=rubygems depName=vagrant-vsphere
vagrant_vsphere_plugin_version: '1.14.0'

# see https://rubygems.org/gems/vagrant-windows-sysprep
# see https://github.com/rgl/vagrant-windows-sysprep
# renovate: datasource=rubygems depName=vagrant-windows-sysprep
vagrant_windows_sysprep_plugin_version: '0.0.10'

provision_username: '{{ ansible_user }}'
provision_password: '{{ ansible_password }}'
