# see apt-cache madison powershell
# see https://github.com/PowerShell/PowerShell/releases
# renovate: datasource=github-releases depName=PowerShell/PowerShell extractVersion=^v(?<version>7\.2\..+)
powershell_version: '7.2.10'
