# see https://github.com/moby/moby/releases
# renovate: datasource=github-releases depName=moby/moby
docker_version: '29.0.1'

# see https://github.com/docker/compose/releases
# renovate: datasource=github-releases depName=docker/compose
docker_compose_version: '2.40.3'
