# see https://github.com/moby/moby/releases
# renovate: datasource=github-releases depName=moby/moby
docker_version: '29.1.4'

# see https://github.com/containerd/containerd/releases
# renovate: datasource=github-releases depName=containerd/containerd
docker_containerd_version: '2.2.1'

# see https://github.com/docker/compose/releases
# renovate: datasource=github-releases depName=docker/compose
docker_compose_version: '5.0.2'
