# see https://github.com/moby/moby/releases
# renovate: datasource=github-releases depName=moby/moby
docker_version: '29.1.3'

# see https://github.com/docker/compose/releases
# renovate: datasource=github-releases depName=docker/compose
docker_compose_version: '5.0.1'
