# see https://github.com/kubernetes/kubernetes/releases
# see https://kubernetes.io/releases/
kubectl_version: '1.24.3'

# see https://github.com/derailed/k9s/releases
k9s_version: '0.26.3'

# see https://github.com/helm/helm/releases
helm_version: '3.9.3'

# see https://github.com/google/go-containerregistry/releases
crane_version: '0.11.0'

# see https://github.com/regclient/regclient/releases
regclient_version: '0.4.4'
