kind_cluster_name: kind
kind_cluster_domain: test
kind_provision_username: '{{ ansible_user }}'
kind_provision_password: '{{ ansible_password }}'

# see https://github.com/kubernetes-sigs/kind/releases
# renovate: datasource=github-releases depName=kubernetes-sigs/kind
kind_version: '0.31.0'

# see https://hub.docker.com/r/kindest/node/tags
# renovate: datasource=docker depName=kindest/node extractVersion=(?<version>1\.35\..+)
kind_node_image_version: '1.35.0'

# see https://github.com/databus23/helm-diff/releases
# renovate: datasource=github-releases depName=databus23/helm-diff
kind_helm_diff_version: '3.15.0'

# see https://artifacthub.io/packages/helm/metallb/metallb
# see https://github.com/metallb/metallb/tree/main/charts/metallb
# see https://github.com/metallb/metallb
# renovate: datasource=helm depName=metallb registryUrl=https://metallb.github.io/metallb
kind_metallb_chart_version: '0.15.3' # app version: 0.15.3

# see https://github.com/cert-manager/cert-manager
# see https://artifacthub.io/packages/helm/cert-manager/cert-manager
# renovate: datasource=helm depName=cert-manager registryUrl=https://charts.jetstack.io
kind_cert_manager_chart_version: '1.19.3' # app version: 1.19.3

# see https://github.com/cert-manager/trust-manager
# see https://artifacthub.io/packages/helm/cert-manager/trust-manager
# renovate: datasource=helm depName=trust-manager registryUrl=https://charts.jetstack.io
kind_trust_manager_chart_version: '0.20.3' # app version: 0.20.3

# see https://github.com/stakater/reloader
# see https://artifacthub.io/packages/helm/stakater/reloader
# renovate: datasource=helm depName=reloader registryUrl=https://stakater.github.io/stakater-charts
kind_reloader_chart_version: '2.2.7' # app version: 1.4.12

# see https://artifacthub.io/packages/helm/traefik/traefik
# renovate: datasource=helm depName=traefik registryUrl=https://helm.traefik.io/traefik
kind_traefik_chart_version: '39.0.0' # app version: 3.6.7

# see https://artifacthub.io/packages/helm/headlamp/headlamp
# renovate: datasource=helm depName=headlamp registryUrl=https://kubernetes-sigs.github.io/headlamp
kind_headlamp_chart_version: '0.39.0' # app version: 0.39.0

# see https://artifacthub.io/packages/helm/external-dns/external-dns
# renovate: datasource=helm depName=external-dns registryUrl=https://kubernetes-sigs.github.io/external-dns
kind_external_dns_chart_version: '1.20.0' # app version: 0.20.0

# see https://hub.docker.com/r/powerdns/pdns-auth-48
# see https://hub.docker.com/search?q=pdns-auth-
# see https://github.com/PowerDNS/pdns/blob/master/Dockerfile-auth
# see https://doc.powerdns.com/authoritative/changelog/
# renovate: datasource=docker depName=powerdns/pdns-auth-48
kind_pdns_version: '4.8.5' # app version: 4.8.5

# see https://artifacthub.io/packages/helm/gitea/gitea
# renovate: datasource=helm depName=gitea registryUrl=https://dl.gitea.com/charts
kind_gitea_chart_version: '12.5.0' # app version: 1.25.4

# see https://artifacthub.io/packages/helm/argo/argo-cd
# renovate: datasource=helm depName=argo-cd registryUrl=https://argoproj.github.io/argo-helm
kind_argocd_chart_version: '9.4.1' # app version: 3.3.0

# see https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
# see https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg
# renovate: datasource=helm depName=cloudnative-pg registryUrl=https://cloudnative-pg.github.io/charts
kind_cnpg_operator_chart_version: '0.27.1' # app version: 1.28.1

# see https://artifacthub.io/packages/helm/cloudnative-pg/cluster
# see https://github.com/cloudnative-pg/charts/tree/main/charts/cluster
# renovate: datasource=helm depName=cluster registryUrl=https://cloudnative-pg.github.io/charts
kind_cnpg_cluster_chart_version: '0.5.0'

# see https://cloudnative-pg.io/docs/1.28/supported_releases
# see https://github.com/cloudnative-pg/charts/tree/main/charts/cluster
kind_cnpg_cluster_postgresql_major_version: '18'

# see https://artifacthub.io/packages/helm/runix/pgadmin4
# renovate: datasource=helm depName=pgadmin4 registryUrl=https://helm.runix.net
kind_pgadmin_chart_version: '1.57.0'

# see https://hub.docker.com/r/dpage/pgadmin4/tags
# renovate: datasource=docker depName=dpage/pgadmin4 versioning=semver-coerced
kind_pgadmin_chart_app_version: '9.12.0'
