base_timezone: 'Europe/Lisbon'

# see https://github.com/git-ecosystem/git-credential-manager/releases
# renovate: datasource=github-releases depName=git-ecosystem/git-credential-manager
base_git_credential_manager_version: '2.7.0'

# see https://github.com/newren/git-filter-repo/releases
# renovate: datasource=github-releases depName=newren/git-filter-repo
base_git_filter_repo_version: '2.47.0'

# see https://github.com/astral-sh/uv/releases
# renovate: datasource=github-releases depName=astral-sh/uv
base_uv_version: '0.10.4'

# see https://github.com/upx/upx/releases
# renovate: datasource=github-releases depName=upx/upx
base_upx_version: '5.1.0'
