# see https://github.com/kubernetes/kubernetes/releases
# see https://kubernetes.io/releases/
# renovate: datasource=github-releases depName=kubernetes/kubernetes extractVersion=(?<version>1\.35\..+)
k8s_client_kubectl_version: '1.35.1'

# see https://github.com/derailed/k9s/releases
# renovate: datasource=github-releases depName=derailed/k9s
k8s_client_k9s_version: '0.50.18'

# see https://github.com/helm/helm/releases
# NB do not upgrade to helm 4.x until the following issue is fixed:
#     https://github.com/ansible-collections/kubernetes.core/issues/1038
# renovate: datasource=github-releases depName=helm/helm extractVersion=v?(?<version>3\..+)
k8s_client_helm_version: '3.20.0'

# see https://github.com/stefanprodan/timoni/releases
# renovate: datasource=github-releases depName=stefanprodan/timoni
k8s_client_timoni_version: '0.25.2'

# see https://github.com/oras-project/oras/releases
# renovate: datasource=github-releases depName=oras-project/oras
k8s_client_oras_version: '1.3.0'

# see https://github.com/google/go-containerregistry/releases
# renovate: datasource=github-releases depName=google/go-containerregistry
k8s_client_crane_version: '0.21.0'

# see https://github.com/regclient/regclient/releases
# renovate: datasource=github-releases depName=regclient/regclient
k8s_client_regclient_version: '0.11.2'

# see https://github.com/cert-manager/cmctl/releases
# renovate: datasource=github-releases depName=cert-manager/cmctl
k8s_client_cmctl_version: '2.4.0'

# see https://github.com/cilium/cilium-cli/releases
# renovate: datasource=github-releases depName=cilium/cilium-cli
k8s_client_cilium_version: '0.19.1'

# see https://github.com/cilium/hubble/releases
# renovate: datasource=github-releases depName=cilium/hubble
k8s_client_hubble_version: '1.18.6'
