- name: Install upx
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install-upx.sh') }}"
  environment:
    UPX_VERSION: "{{ base_upx_version }}"
  register: base_result
  changed_when: "'ANSIBLE CHANGED NO' not in base_result.stdout_lines"

# - name: Install uv bash completion
#   block:
#     - name: Get uv bash completion
#       ansible.builtin.command: uv generate-shell-completion bash
#       register: base_bash_completion
#       changed_when: false
#     - name: Install uv bash completion
#       ansible.builtin.copy:
#         content: "{{ base_bash_completion.stdout }}"
#         dest: /usr/share/bash-completion/completions/uv
#         mode: 0444
