- name: Install cue
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'install.sh') }}"
  environment:
    CUE_VERSION: "{{ cue_version }}"
  register: result
  changed_when: "'ANSIBLE CHANGED NO' not in result.stdout_lines"

- name: Install cue bash completion
  block:
    - name: Get cue bash completion
      ansible.builtin.shell: cue completion bash
      register: bash_completion
      changed_when: false
    - name: Install cue bash completion
      ansible.builtin.copy:
        content: "{{ bash_completion.stdout }}"
        dest: /usr/share/bash-completion/completions/cue
        mode: 0444
