# see https://github.com/hashicorp/terraform/releases
# renovate: datasource=github-releases depName=hashicorp/terraform
terraform_version: '1.9.6'

# see https://github.com/nbering/terraform-inventory/releases
# renovate: datasource=github-releases depName=nbering/terraform-inventory
terraform_inventory_version: '2.2.0'
